#!/usr/bin/env python3
"""Export V2 design CSV files into a deterministic Lua data module."""

from __future__ import annotations

import csv
import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE_DIR = ROOT / "design" / "v2" / "data"
OUTPUT = ROOT / "bin" / "res" / "scripts" / "LuaClass" / "V2ChapterData.lua"
TABLES = (
    "chapter",
    "resource",
    "map_node",
    "map_edge",
    "event",
    "event_choice",
    "crew",
    "ship_module",
    "enemy",
    "reward",
    "dialogue",
    "route",
    "balance",
    "battle_action",
    "presentation",
    "audio_cue",
    "telemetry_event",
    "quality_gate",
)


def lua_value(value: str) -> str:
    if re.fullmatch(r"-?\d+", value):
        return value
    if re.fullmatch(r"-?\d+\.\d+", value):
        return value
    return json.dumps(value, ensure_ascii=False)


def export() -> str:
    lines = [
        "-- Generated by tools/v2/export_runtime.py. Do not edit by hand.",
        "-- Source of truth: design/v2/data/*.csv",
        "",
        "local data = {",
    ]

    for table_name in TABLES:
        source = SOURCE_DIR / f"{table_name}.csv"
        with source.open(encoding="utf-8", newline="") as handle:
            rows = list(csv.DictReader(handle))
        lines.append(f"    {table_name} = {{")
        for row in rows:
            fields = [
                f"{key} = {lua_value(value)}"
                for key, value in row.items()
                if value != ""
            ]
            lines.append("        { " + ", ".join(fields) + " },")
        lines.append("    },")
    lines.extend(
        [
            "}",
            "",
            "data.by_id = {}",
            "for _, tableName in ipairs({",
            *[f'    "{table_name}",' for table_name in TABLES],
            "}) do",
            "    data.by_id[tableName] = {}",
            "    for _, row in ipairs(data[tableName]) do",
            "        data.by_id[tableName][row.id] = row",
            "    end",
            "end",
            "",
            "return data",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the generated module is stale")
    args = parser.parse_args()
    content = export()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            raise SystemExit("V2ChapterData.lua is stale; run tools/v2/export_runtime.py")
        print("V2 runtime export is current")
        return
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Exported {len(TABLES)} V2 tables to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
